name: codal-buildtarget

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: letssteam/makecode-toolchain:latest
      options: --user 1001 --security-opt no-new-privileges
    steps:
      - name: checkout codal
        uses: actions/checkout@v2
        with:
          repository: letssteam/codal-letssteam
          path: codal-letssteam
      - name: codal build
        run: |
          cd codal-letssteam
          make build_all
